\connect thirdparty

CREATE ROLE "cdcUser" WITH REPLICATION LOGIN PASSWORD 'cdcUser';
CREATE ROLE CDC_REPLICATION_GROUP;
GRANT CDC_REPLICATION_GROUP TO "cdcUser";
GRANT CDC_REPLICATION_GROUP TO "postgres";
ALTER TABLE public."tenants" OWNER TO CDC_REPLICATION_GROUP;
ALTER TABLE public."thirdparties" OWNER TO CDC_REPLICATION_GROUP;
ALTER TABLE public."contacts" OWNER TO CDC_REPLICATION_GROUP;
GRANT CREATE ON DATABASE thirdparty TO "cdcUser";